Implementation of basic Dataset trait and MNIST Dataset
utilForever/polarlight pull request #10
Opened 2022-07-31 08:09 UTC by litcoderr

[Done]
- Defined basic Dataset trait
    - len() method
    - get_item() method
- Made builtin MNIST dataset
    - download file from link
    - decompress file
    - implemented `len()` and `get_item()` method from Dataset trait
    - implemented Debug trait for cli visualization
![image](https://user-images.githubusercontent.com/41692376/182016248-2c212e76-9475-4e21-8e68-957f182f755b.png)

[Todo]
- Make Dataloader for multi-processor batching sequence
- Specify DatasetItem trait when Tensor is usable

2022-08-02 13:40 UTC, utilForever requested changes
You should change many things. Please check them.
I'll review again after you resolved these issues.

2022-08-02 13:40 UTC, utilForever commented on .gitignore
> +raw
What is this? Can you add comment for the meaning of this line?

2022-08-02 13:40 UTC, utilForever commented on src/utils/data.rs
> +/// Downloading process will only be proceeded when file path does not exist
```suggestion
/// Download process will be proceeded when the file path does not exist.
```

2022-08-02 13:40 UTC, utilForever commented on src/utils/data.rs
> +/// * `url` - Url where original data is stored
```suggestion
/// * `root` - The root directory of dataset
/// * `file_name` - The file name to download
/// * `url` - URL where the original data is stored
```

2022-08-02 13:40 UTC, utilForever commented on src/utils/data.rs
> +    decompress: bool,
1. Where is the comment for parameter `decompress`?
2. I suggest to rename this parameter.

```suggestion
    is_decompress: bool,
```

2022-08-02 13:40 UTC, utilForever commented on src/utils/data.rs
> +    Ok(())
I think that line-by-line comments are unnecessary.
Minimize comments by improving readability such as variable renaming.

2022-08-02 13:40 UTC, utilForever commented on src/utils/data.rs
> +/// * `big_endian` : Boolean for if data is stored as big_endian
```suggestion
/// * `byte_arr` : The original byte array
/// * `offset` : The offset of the byte array to convert
/// * `is_big_endian` : A flag indicates the data is stored as big endian
```

2022-08-02 13:40 UTC, utilForever commented on src/utils/data.rs
> +fn byte_arr_to_u32(byt: &Vec<u8>, offset: u32, big_endian: bool) -> u32 {
```suggestion
fn convert_byte_arr_to_u32(byte_arr: &Vec<u8>, offset: u32, is_big_endian: bool) -> u32 {
```

2022-08-02 13:40 UTC, utilForever commented on src/utils/data/dataset.rs
> +    /// * `raw` - raw data on memory
```suggestion
    /// * `raw` - The raw data on memory
```

2022-08-02 13:40 UTC, utilForever commented on src/utils/data/dataset.rs
> +    impl OnMemData {
```suggestion
    }
    
    impl OnMemData {
```

2022-08-02 13:40 UTC, utilForever commented on src/utils/data/dataset.rs
> +        /// * `source` - file online source
```suggestion
        /// * `root` - The root directory
        /// * `file_name` - The downloaded file name
        /// * `source` - The source URL to download
```

2022-08-02 13:40 UTC, utilForever commented on src/utils/data/dataset.rs
> +            // load file to memory
```suggestion
            // Load file to memory
```

2022-08-02 13:40 UTC, utilForever commented on src/utils/data/dataset.rs
> +    /// * `col` - col size
```suggestion
    /// * `image` - The image vector
    /// * `label` - The label (ranging from 0 to 9)
    /// * `row` - The row size
```

2022-08-02 13:40 UTC, utilForever commented on src/utils/data/dataset.rs
> +    impl fmt::Debug for MnistItem {
```suggestion
    }
    
    impl DatasetItem for MnistItem {}
    
    impl fmt::Debug for MnistItem {
```

2022-08-02 13:40 UTC, utilForever commented on src/utils/data/dataset.rs
> +                if (i + 1) as u32 % self.row == 0 {
```suggestion
                }
                
                if (i + 1) as u32 % self.row == 0 {
```

2022-08-02 13:40 UTC, utilForever commented on src/utils/data/dataset.rs
> +            write!(f, "{}{}", label_str, image_str)
```suggestion
            }
            
            write!(f, "{}{}", label_str, image_str)
```

2022-08-02 13:40 UTC, utilForever commented on src/utils/data/dataset.rs
> +    /// * `root` - Root directory of dataset
Incorrect comments for parameters. Please rewrite it.

2022-08-02 13:40 UTC, utilForever commented on src/utils/data/dataset.rs
> +    impl MNIST {
```suggestion
    }
    
    impl MNIST {
```

2022-08-02 13:40 UTC, utilForever commented on src/utils/data/dataset.rs
> +        fn new(root: PathBuf, test: bool) -> Result<MNIST, Box<dyn error::Error>> {
```suggestion
        /// * `root` - The root directory of dataset
        /// * `is_test` - true: downloads test set, false: downloads train set
        fn new(root: PathBuf, is_test: bool) -> Result<MNIST, Box<dyn error::Error>> {
```

2022-08-02 13:40 UTC, utilForever commented on src/utils/data/dataset.rs
> +                Ok(MNIST {
```suggestion
                )?);
                
                Ok(MNIST {
```

2022-08-02 13:40 UTC, utilForever commented on src/utils/data/dataset.rs
> +                Ok(MNIST {
```suggestion
                )?);
                
                Ok(MNIST {
```

2022-08-02 13:40 UTC, utilForever commented on src/utils/data/dataset.rs
> +        /// Returns [N_ROW, N_COL] vector
```suggestion
        /// Returns [N_ROW, N_COL] vector of each image.
```

2022-08-02 13:40 UTC, utilForever commented on src/utils/data/dataset.rs
> +                }
```suggestion
                if let Some(image) = &self.test_img {
                    image_data = Some(image);
                }
```

2022-08-02 13:40 UTC, utilForever commented on src/utils/data/dataset.rs
> +                }
```suggestion
                if let Some(image) = &self.train_img {
                    image_data = Some(image);
                }
```

2022-08-02 13:40 UTC, utilForever commented on src/utils/data/dataset.rs
> +            if let Some(image_) = image_data {
```suggestion
            let mut n_cols: u32 = 0;
            
            if let Some(image) = image_data {
```

2022-08-02 13:40 UTC, utilForever commented on src/utils/data/dataset.rs
> +            vec![n_rows, n_cols]
```suggestion
            }
            
            vec![n_rows, n_cols]
```

2022-08-02 13:40 UTC, utilForever commented on src/utils/data/dataset.rs
> +                n_cols = byte_arr_to_u32(&image_.raw, 12, true);
```suggestion
                n_rows = byte_arr_to_u32(&image.raw, 8, true);
                n_cols = byte_arr_to_u32(&image.raw, 12, true);
```

2022-08-02 13:40 UTC, utilForever commented on src/utils/data/dataset.rs
> +    impl Dataset<MnistItem> for MNIST {
```suggestion
    }
    
    impl Dataset<MnistItem> for MNIST {
```

2022-08-02 13:40 UTC, utilForever commented on src/utils/data/dataset.rs
> +            if self.test {
```suggestion
            let mut label: Option<&OnMemData> = None;
            
            if self.test {
```

2022-08-02 13:40 UTC, utilForever commented on src/utils/data/dataset.rs
> +        test: bool,
```suggestion
        is_test: bool,
```

2022-08-02 13:40 UTC, utilForever commented on src/utils/data/dataset.rs
> +            }
```suggestion
                if let Some(label) = &self.test_label {
                    label = Some(label);
                }
            } else {
                if let Some(label) = &self.train_label {
                    label = Some(label);
                }
            }
```

2022-08-02 13:40 UTC, utilForever commented on src/utils/data/dataset.rs
> +        fn get_item(&self, idx: u32) -> Result<MnistItem, Box<dyn error::Error>> {
Where is the documentation for parameters?

2022-08-02 13:40 UTC, utilForever commented on src/utils/data/dataset.rs
> +            }
```suggestion
            if self.test {
                if let Some(label) = &self.test_label {
                    label_data = Some(label);
                }
                if let Some(image) = &self.test_img {
                    image_data = Some(image);
                }
            } else {
                if let Some(label) = &self.train_label {
                    label_data = Some(label);
                }
                if let Some(image) = &self.train_img {
                    image_data = Some(image);
                }
            }
```

2022-08-02 13:40 UTC, utilForever commented on src/utils/data/dataset.rs
> +            }
```suggestion
            let mut image_vec = Vec::new();
            
            if let Some(image) = image_data {
                let size = n_rows * n_cols;
                let start_idx = 16 + size * idx;
                
                for idx in start_idx..start_idx + size {
                    image_vec.push(image.raw[idx as usize]);
                }
            }
```

2022-08-02 13:40 UTC, utilForever commented on src/utils/data/dataset.rs
> +            }
```suggestion
            let mut item_label = 0;
            
            if let Some(label) = label_data {
                item_label = label.raw[(8 + idx) as usize];
            }
```

2022-08-02 13:40 UTC, utilForever commented on src/utils/data/dataset.rs
> +            };
```suggestion
            let item = MnistItem {
                image: image_vec,
                label: item_label,
                row: n_rows,
            };
```

2022-08-02 13:40 UTC, utilForever commented on src/utils/data/dataset.rs
> +    /// Test code for builtin datasets
I think that it is unnecessary.

2022-08-02 13:40 UTC, utilForever commented on src/utils/data/dataset.rs
> +            }
```suggestion
            if let Ok(mnist_test) = MNIST::new(PathBuf::from("raw"), true) {
                let dataset_length = mnist_test.len();
                assert_eq!(dataset_length, 10000);
                
                if let Ok(dataset_item) = mnist_test.get_item(0) {
                    println!("{:?}", dataset_item);
                }
            }
```

2022-08-08 13:02 UTC, litcoderr commented on .gitignore
> +raw
https://github.com/utilForever/polarlight/blob/cc85ee143a695b0622215c619f76617a06782b58/src/utils/data/dataset.rs#L118

`raw` directory is created inside the main project directory whenever the mnist test code is ran.

Should I add some comment in gitignore file

or 

should I change to test code to store mnist data somewhere else?

2022-08-10 11:34 UTC, litcoderr commented
@utilForever I resolved all of your requested changes !!

2022-08-23 13:38 UTC, utilForever approved these changes
LGTM now. Thanks for you work! 🎉

2022-08-23 13:40 UTC, merged