Tensor unsqueeze and cat implemented
utilForever/polarlight pull request #13
Opened 2022-08-23 08:49 UTC by litcoderr

[Done]
- `unsqueeze`: this function expands a tensor's dimension
- `cat`: this function concatenates multiple tensors along a desired axis

2022-08-23 14:32 UTC, utilForever requested changes
You should run `cargo fmt` and `cargo clippy`.

2022-08-23 14:32 UTC, utilForever commented on src/tensor/mod.rs
> +        new_shape[dim] = tensors.len() as i32;
```suggestion
        let mut new_shapes = tensors[0].shape.clone();
        new_shapes[dim] = tensors.len() as i32;
```

2022-08-23 14:32 UTC, utilForever commented on src/tensor/mod.rs
> +        let new_shape_pi = Tensor::<T>::get_shape_pi(&new_shape);
```suggestion
        let new_shape_pi = Tensor::<T>::get_shape_pi(&new_shapes);
```

2022-08-23 14:32 UTC, utilForever commented on src/tensor/mod.rs
> +        }
```suggestion
        tensors.iter().zip(new_shapes.iter().enumerate()).for_each(|(tensor, (idx, new_shape))| {
            if idx != dim && tensor.shape[idx] != *new_shape {
                panic!("The tensors' shape should be the same except for the concatenation dimension");
            }
        });
```

2022-08-23 14:32 UTC, utilForever commented on src/tensor/mod.rs
> +        }
```suggestion
        let new_size = new_shapes.iter().fold(1, |acc, x| acc * x);
```

2022-08-23 14:32 UTC, utilForever commented on src/tensor/mod.rs
> +            let origin_component= tensors[tensor_idx].components[origin_idx].clone();
```suggestion
            let origin_component = tensors[tensor_idx].components[origin_idx].clone();
```

2022-08-23 14:32 UTC, utilForever commented on src/tensor/mod.rs
> +        Tensor::build(new_shape, components)
```suggestion
        Tensor::build(new_shapes, components)
```

2022-08-23 14:32 UTC, utilForever commented on src/tensor/mod.rs
> +            let pi = shape[idx+1] * shape_pi[0];
```suggestion
        for idx in (0..shape.len() - 1).rev() {
            let pi = shape[idx + 1] * shape_pi[0];
```

2022-09-01 08:17 UTC, utilForever approved these changes
LGTM now. Thanks for your work! 🦖

2022-09-01 08:18 UTC, litcoderr commented
No problemo

2022-09-01 08:18 UTC, merged